# channels.py — Channel list extracted from tvonlinehd.com.br
# Each channel has: id, name, category, logo, players[], direct_m3u8 (optional)

CHANNELS = [
    # ─── ESPORTES ────────────────────────────────────────────────────────────
    {
        "id": "sportv1",
        "name": "SPORTV 1",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/sportv.png",
        "players": [
            "https://joel.embedtv.live/sportv",
            "https://sinalpublicoetv.vercel.app/?id=sportv1",
            "https://rdcanais.com/sportv",
            "https://redecanaistv.be/player3/ch.php?canal=sportv1",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "sportv2",
        "name": "SPORTV 2",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/sportv2.png",
        "players": [
            "https://joel.embedtv.live/sportv2",
            "https://sinalpublicoetv.vercel.app/?id=sportv2",
            "https://rdcanais.com/sportv2",
            "https://redecanaistv.be/player3/ch.php?canal=sportv2",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "sportv3",
        "name": "SPORTV 3",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/sportv3.png",
        "players": [
            "https://joel.embedtv.live/sportv3",
            "https://sinalpublicoetv.vercel.app/?id=sportv3",
            "https://rdcanais.com/sportv3",
            "https://redecanaistv.be/player3/ch.php?canal=sportv3",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn",
        "name": "ESPN",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn",
            "https://sinalpublicoetv.vercel.app/?id=espn1",
            "https://rdcanais.com/espn",
            "https://redecanaistv.be/player3/ch.php?canal=espn",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn2",
        "name": "ESPN 2",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn2",
            "https://sinalpublicoetv.vercel.app/?id=espn2",
            "https://rdcanais.com/espn2",
            "https://redecanaistv.be/player3/ch.php?canal=espn2",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn3",
        "name": "ESPN 3",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn3",
            "https://sinalpublicoetv.vercel.app/?id=espn3",
            "https://rdcanais.com/espn3",
            "https://redecanaistv.be/player3/ch.php?canal=espn3",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn4",
        "name": "ESPN 4",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn4",
            "https://sinalpublicoetv.vercel.app/?id=espn4",
            "https://rdcanais.com/espn4",
            "https://redecanaistv.be/player3/ch.php?canal=espn4",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn5",
        "name": "ESPN 5",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn5",
            "https://sinalpublicoetv.vercel.app/?id=espn5",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "espn6",
        "name": "ESPN 6",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/espn.png",
        "players": [
            "https://joel.embedtv.live/espn6",
            "https://sinalpublicoetv.vercel.app/?id=espn6",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "premiere",
        "name": "PREMIERE",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": [
            "https://joel.embedtv.live/premiere",
            "https://sinalpublicoetv.vercel.app/?id=premiereclubes",
            "https://rdcanais.com/premiereclubes",
            "https://redecanaistv.be/player3/ch.php?canal=premiereclubes",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "premiere2",
        "name": "Premiere 2",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere2"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere3",
        "name": "Premiere 3",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere3"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere4",
        "name": "Premiere 4",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere4"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere5",
        "name": "Premiere 5",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere5"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere6",
        "name": "Premiere 6",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere6"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere7",
        "name": "Premiere 7",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere7"],
        "direct_m3u8": None,
    },
    {
        "id": "premiere8",
        "name": "Premiere 8",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/premiere.png",
        "players": ["https://joel.embedtv.live/premiere8"],
        "direct_m3u8": None,
    },
    {
        "id": "bandsports",
        "name": "BAND SPORTS",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/bandsports.png",
        "players": ["https://joel.embedtv.live/bandsports"],
        "direct_m3u8": None,
    },
    {
        "id": "cazetv",
        "name": "CazéTV",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/cazetv.png",
        "players": ["https://joel.embedtv.live/cazetv"],
        "direct_m3u8": None,
    },
    {
        "id": "combate",
        "name": "COMBATE",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/combate.png",
        "players": ["https://joel.embedtv.live/combate"],
        "direct_m3u8": None,
    },
    {
        "id": "dazn",
        "name": "DAZN",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/dazn.png",
        "players": ["https://joel.embedtv.live/dazn"],
        "direct_m3u8": None,
    },
    {
        "id": "disneyplus",
        "name": "Disney+",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/disneyplus.png",
        "players": ["https://joel.embedtv.live/disneyplus"],
        "direct_m3u8": None,
    },
    {
        "id": "nossofutebol",
        "name": "NOSSO FUTEBOL",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/nossofutebol.png",
        "players": ["https://joel.embedtv.live/nossofutebol"],
        "direct_m3u8": None,
    },
    {
        "id": "nsports",
        "name": "N Sports",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/nsports.png",
        "players": ["https://joel.embedtv.live/nsports"],
        "direct_m3u8": None,
    },
    {
        "id": "xsports",
        "name": "Xsports",
        "category": "esportes",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVIWMFBFMCFOWNhSQrIYvkHj2jZgv7QLljg&s",
        "players": ["https://joel.embedtv.live/xsports"],
        "direct_m3u8": None,
    },
    {
        "id": "ufcfightpass",
        "name": "UFC Fight Pass",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/ufcfightpass.png",
        "players": ["https://joel.embedtv.live/ufcfightpass"],
        "direct_m3u8": None,
    },
    {
        "id": "tntsports",
        "name": "TNT SPORTS",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/tnt.png",
        "players": ["https://joel.embedtv.live/tnt"],
        "direct_m3u8": None,
    },
    {
        "id": "off",
        "name": "Canal Off",
        "category": "esportes",
        "logo": "https://embedtv.live/assets/images/off.png",
        "players": ["https://joel.embedtv.live/off"],
        "direct_m3u8": None,
    },
    {
        "id": "tvfifa",
        "name": "TV FIFA",
        "category": "esportes",
        "logo": "https://static.vecteezy.com/ti/vetor-gratis/p1/14470970-logotipo-oficial-da-fifa-design-de-simbolo-preto-e-branco-ilustracaoial-abstrata-gratis-vetor.jpg",
        "players": [],
        "direct_m3u8": "https://c2657533.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UGxleC1icl9GSUZBUGx1c1BvcnR1Z3Vlc2VfSExT/playlist.m3u8",
    },
    {
        "id": "primevideo",
        "name": "PRIME VIDEO 1",
        "category": "esportes",
        "logo": "https://xatimg.com/image/DDsyPtVFwjBM.jpg",
        "players": ["https://joel.embedtv.live/primevideo"],
        "direct_m3u8": None,
    },
    # ─── PORTUGAL ESPORTES ───────────────────────────────────────────────────
    {
        "id": "pt_abola",
        "name": "PT - A Bola",
        "category": "esportes",
        "logo": "https://xatimg.com/image/a1uWLwzRJgJo.jpg",
        "players": ["https://joel.embedtv.live/pt_abola"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_benficatv",
        "name": "PT - Benfica TV",
        "category": "esportes",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ7g4bs4V8Ox9rN0QNSvM_sZn-A7KvF7UzeQ&s",
        "players": ["https://joel.embedtv.live/pt_benficatv"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_canal11",
        "name": "Canal 11",
        "category": "esportes",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWhaP4oFrwpvKqZ1MY5HsesuQSSUF3e_neDQ&s",
        "players": ["https://joel.embedtv.live/pt_canal11"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_eleven1",
        "name": "PT - Eleven 1",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_eleven1.webp",
        "players": ["https://joel.embedtv.live/pt_eleven1"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_eleven2",
        "name": "PT - Eleven 2",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_eleven2.webp",
        "players": ["https://joel.embedtv.live/pt_eleven2"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_eleven3",
        "name": "PT - Eleven 3",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_eleven3.webp",
        "players": ["https://joel.embedtv.live/pt_eleven3"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv1",
        "name": "PT - Sporttv 1",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv1.webp",
        "players": ["https://joel.embedtv.live/pt_sportv1"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv2",
        "name": "PT - Sporttv 2",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv2.webp",
        "players": ["https://joel.embedtv.live/pt_sportv2"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv3",
        "name": "PT - Sporttv 3",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv3.webp",
        "players": ["https://joel.embedtv.live/pt_sportv3"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv4",
        "name": "PT - Sporttv 4",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv3.webp",
        "players": ["https://joel.embedtv.live/pt_sportv4"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv5",
        "name": "PT - Sporttv 5",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv5.webp",
        "players": ["https://joel.embedtv.live/pt_sportv5"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv6",
        "name": "PT - Sporttv 6",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv2.webp",
        "players": ["https://joel.embedtv.live/pt_sportv6"],
        "direct_m3u8": None,
    },
    {
        "id": "pt_sportv7",
        "name": "PT - Sporttv 7",
        "category": "esportes",
        "logo": "https://cdn.faz-o-eli.online/preview/pt_sportv3.webp",
        "players": ["https://joel.embedtv.live/pt_sportv7"],
        "direct_m3u8": None,
    },
    # ─── TV ABERTA ───────────────────────────────────────────────────────────
    {
        "id": "globorj",
        "name": "GLOBO RJ",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": [
            "https://joel.embedtv.live/globorj",
            "https://sinalpublicoetv.vercel.app/?id=globorj",
            "https://rdcanais.com/globorj",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "globosp",
        "name": "GLOBO SP",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": [
            "https://joel.embedtv.live/globosp",
            "https://sinalpublicoetv.vercel.app/?id=globosp",
            "https://rdcanais.com/globosp",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "globomg",
        "name": "GLOBO MG",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": [
            "https://joel.embedtv.live/globomg",
            "https://sinalpublicoetv.vercel.app/?id=globomg",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "globors",
        "name": "GLOBO RS",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": [
            "https://joel.embedtv.live/globors",
            "https://sinalpublicoetv.vercel.app/?id=globors",
        ],
        "direct_m3u8": None,
    },
    {
        "id": "globopb",
        "name": "GLOBO PB",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": ["https://joel.embedtv.live/globopb"],
        "direct_m3u8": None,
    },
    {
        "id": "globope",
        "name": "GLOBO PE",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": ["https://joel.embedtv.live/globope"],
        "direct_m3u8": None,
    },
    {
        "id": "globoam",
        "name": "GLOBO AM",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": ["https://joel.embedtv.live/globoam"],
        "direct_m3u8": None,
    },
    {
        "id": "globoes",
        "name": "GLOBO ES",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": ["https://joel.embedtv.live/globoes"],
        "direct_m3u8": None,
    },
    {
        "id": "globoce",
        "name": "GLOBO CE",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/globo.png",
        "players": ["https://joel.embedtv.live/globoce"],
        "direct_m3u8": None,
    },
    {
        "id": "band",
        "name": "BAND",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/band.png",
        "players": [
            "https://joel.embedtv.live/band",
            "https://sinalpublicoetv.vercel.app/?id=band",
        ],
        "direct_m3u8": "https://cdn-5.nxplay.com.br/BAND_HD_PFZ_NX/index.m3u8",
    },
    {
        "id": "recordmg",
        "name": "Record MG",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/record.png",
        "players": ["https://joel.embedtv.live/recordmg"],
        "direct_m3u8": "https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/playlist.m3u8",
    },
    {
        "id": "recordrj",
        "name": "Record RJ",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/record.png",
        "players": ["https://joel.embedtv.live/recordrj"],
        "direct_m3u8": "https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/playlist.m3u8",
    },
    {
        "id": "recordsp",
        "name": "Record SP",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/record.png",
        "players": ["https://joel.embedtv.live/recordsp"],
        "direct_m3u8": "https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/playlist.m3u8",
    },
    {
        "id": "redetv",
        "name": "RedeTV!",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/redetv.png",
        "players": ["https://joel.embedtv.live/redetv"],
        "direct_m3u8": "https://streaming.cloudecast.com/hls/redetves/index.m3u8",
    },
    {
        "id": "sbtsp",
        "name": "SBT SP",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/sbt.png",
        "players": [],
        "direct_m3u8": "https://d1jvs4svzaqp8n.cloudfront.net/v1/master/215c0da80606fed29372070168106400a6ca7e1a/SSAI_TITAN_V3/indexMobile.m3u8",
    },
    {
        "id": "sbtrj",
        "name": "SBT RJ",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/sbt.png",
        "players": [],
        "direct_m3u8": "https://d1jvs4svzaqp8n.cloudfront.net/v1/master/215c0da80606fed29372070168106400a6ca7e1a/SSAI_TITAN_V3/indexMobile.m3u8",
    },
    {
        "id": "tvcultura",
        "name": "TV Cultura",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/tvcultura.png",
        "players": [],
        "direct_m3u8": "https://player-tvcultura.stream.uol.com.br/live/tvcultura.m3u8",
    },
    {
        "id": "gnt",
        "name": "GNT",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/gnt.png",
        "players": ["https://joel.embedtv.live/gnt"],
        "direct_m3u8": None,
    },
    {
        "id": "gloob",
        "name": "Gloob",
        "category": "tv-aberta",
        "logo": "https://embedtv.live/assets/images/gloob.png",
        "players": ["https://joel.embedtv.live/gloob"],
        "direct_m3u8": None,
    },
    {
        "id": "tvbrasil",
        "name": "TV Brasil",
        "category": "tv-aberta",
        "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/TV_Brasil_logo.svg/960px-TV_Brasil_logo.svg.png",
        "players": [],
        "direct_m3u8": "https://tvbrasil-stream.ebc.com.br/index.m3u8",
    },
    {
        "id": "redebrasil",
        "name": "Rede Brasil",
        "category": "tv-aberta",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjpyzGehmBWymkC0bbV-oLhjONP8dwTn2i94FSXq78sA&s",
        "players": [],
        "direct_m3u8": "https://video09.logicahost.com.br/redebrasiloficial/redebrasiloficial/playlist.m3u8",
    },
    {
        "id": "tvgazeta",
        "name": "TV Gazeta SP",
        "category": "tv-aberta",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdElbuUmX-kA3cz4ogzriQ4RfXlU2OTBAqLA&s",
        "players": [],
        "direct_m3u8": "https://video08.logicahost.com.br/tvc21/tvc21/playlist.m3u8",
    },
    # ─── FILMES E SÉRIES ─────────────────────────────────────────────────────
    {
        "id": "ae",
        "name": "A&E",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/ae.png",
        "players": ["https://joel.embedtv.live/ae"],
        "direct_m3u8": None,
    },
    {
        "id": "amc",
        "name": "AMC",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/amc.png",
        "players": ["https://joel.embedtv.live/amc"],
        "direct_m3u8": None,
    },
    {
        "id": "axn",
        "name": "AXN",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/axn.png",
        "players": ["https://joel.embedtv.live/axn"],
        "direct_m3u8": None,
    },
    {
        "id": "cinemax",
        "name": "CINEMAX",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/cinemax.png",
        "players": ["https://joel.embedtv.live/cinemax"],
        "direct_m3u8": None,
    },
    {
        "id": "viva",
        "name": "GLOBO PLAY NOVELAS",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/viva.png",
        "players": ["https://joel.embedtv.live/viva"],
        "direct_m3u8": None,
    },
    {
        "id": "hbo",
        "name": "HBO",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hbo.png",
        "players": ["https://joel.embedtv.live/hbo"],
        "direct_m3u8": None,
    },
    {
        "id": "hbo2",
        "name": "HBO 2",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hbo2.png",
        "players": ["https://joel.embedtv.live/hbo2"],
        "direct_m3u8": None,
    },
    {
        "id": "hbofamily",
        "name": "HBO FAMILY",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hbofamily.png",
        "players": ["https://joel.embedtv.live/hbofamily"],
        "direct_m3u8": None,
    },
    {
        "id": "hbomundi",
        "name": "HBO MUNDI",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hbomundi.png",
        "players": ["https://joel.embedtv.live/hbomundi"],
        "direct_m3u8": None,
    },
    {
        "id": "hboplus",
        "name": "HBO PLUS",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hboplus.png",
        "players": ["https://joel.embedtv.live/hboplus"],
        "direct_m3u8": None,
    },
    {
        "id": "hbopop",
        "name": "HBO POP",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hbopop.png",
        "players": ["https://joel.embedtv.live/hbopop"],
        "direct_m3u8": None,
    },
    {
        "id": "hboxtreme",
        "name": "HBO XTREME",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/hboxtreme.png",
        "players": ["https://joel.embedtv.live/hboxtreme"],
        "direct_m3u8": None,
    },
    {
        "id": "megapix",
        "name": "MEGA PIX",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/megapix.png",
        "players": ["https://joel.embedtv.live/megapix"],
        "direct_m3u8": None,
    },
    {
        "id": "sonychannel",
        "name": "SONY CHANNEL",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/sonychannel.png",
        "players": ["https://joel.embedtv.live/sonychannel"],
        "direct_m3u8": None,
    },
    {
        "id": "studiouniversal",
        "name": "Studio Universal",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/studiouniversal.png",
        "players": ["https://joel.embedtv.live/studiouniversal"],
        "direct_m3u8": None,
    },
    {
        "id": "telecineaction",
        "name": "TELECINE ACTION",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecineaction.png",
        "players": ["https://joel.embedtv.live/telecineaction"],
        "direct_m3u8": None,
    },
    {
        "id": "telecinecult",
        "name": "TELECINE CULT",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecinecult.png",
        "players": ["https://joel.embedtv.live/telecinecult"],
        "direct_m3u8": None,
    },
    {
        "id": "telecinefun",
        "name": "TELECINE FUN",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecinefun.png",
        "players": ["https://joel.embedtv.live/telecinefun"],
        "direct_m3u8": None,
    },
    {
        "id": "telecinepipoca",
        "name": "TELECINE PIPOCA",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecinepipoca.png",
        "players": ["https://joel.embedtv.live/telecinepipoca"],
        "direct_m3u8": None,
    },
    {
        "id": "telecinepremium",
        "name": "TELECINE PREMIUM",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecinepremium.png",
        "players": ["https://joel.embedtv.live/telecinepremium"],
        "direct_m3u8": None,
    },
    {
        "id": "telecinetouch",
        "name": "TELECINE TOUCH",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/telecinetouch.png",
        "players": ["https://joel.embedtv.live/telecinetouch"],
        "direct_m3u8": None,
    },
    {
        "id": "tnt",
        "name": "TNT",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/tnt.png",
        "players": ["https://joel.embedtv.live/tnt"],
        "direct_m3u8": None,
    },
    {
        "id": "tntnovelas",
        "name": "TNT NOVELAS",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/tntnovelas.png",
        "players": ["https://joel.embedtv.live/tntnovelas"],
        "direct_m3u8": None,
    },
    {
        "id": "tntseries",
        "name": "TNT SERIES",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/tntseries.png",
        "players": ["https://joel.embedtv.live/tntseries"],
        "direct_m3u8": None,
    },
    {
        "id": "universaltv",
        "name": "UNIVERSAL TV",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/universaltv.png",
        "players": ["https://joel.embedtv.live/universaltv"],
        "direct_m3u8": None,
    },
    {
        "id": "warner",
        "name": "WARNER TV",
        "category": "filmes-e-series",
        "logo": "https://embedtv.live/assets/images/warnerchannel.png",
        "players": ["https://joel.embedtv.live/warner"],
        "direct_m3u8": None,
    },
    # ─── VARIEDADES ──────────────────────────────────────────────────────────
    {
        "id": "adultswim",
        "name": "Adult Swim",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/adultswim.png",
        "players": ["https://joel.embedtv.live/adultswim"],
        "direct_m3u8": None,
    },
    {
        "id": "animalplanet",
        "name": "ANIMAL PLANET",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/animalplanet.png",
        "players": ["https://joel.embedtv.live/animalplanet"],
        "direct_m3u8": None,
    },
    {
        "id": "comedycentral",
        "name": "COMEDY CENTRAL",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/comedycentral.png",
        "players": ["https://joel.embedtv.live/comedycentral"],
        "direct_m3u8": None,
    },
    {
        "id": "discoverychannel",
        "name": "DISCOVERY CHANNEL",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoverychannel.png",
        "players": ["https://joel.embedtv.live/discoverychannel"],
        "direct_m3u8": None,
    },
    {
        "id": "discoveryhh",
        "name": "Discovery Home & Health",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoveryhh.png",
        "players": ["https://joel.embedtv.live/discoveryhh"],
        "direct_m3u8": None,
    },
    {
        "id": "discoveryid",
        "name": "Investigation Discovery",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoverychannel.png",
        "players": ["https://joel.embedtv.live/discoveryid"],
        "direct_m3u8": None,
    },
    {
        "id": "discoveryscience",
        "name": "Discovery Science",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoveryscience.png",
        "players": ["https://joel.embedtv.live/discoveryscience"],
        "direct_m3u8": None,
    },
    {
        "id": "discoverytheater",
        "name": "Discovery Theater",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoverytheater.png",
        "players": ["https://joel.embedtv.live/discoverytheater"],
        "direct_m3u8": None,
    },
    {
        "id": "discoveryturbo",
        "name": "Discovery Turbo",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoveryturbo.png",
        "players": ["https://joel.embedtv.live/discoveryturbo"],
        "direct_m3u8": None,
    },
    {
        "id": "discoveryworld",
        "name": "Discovery World",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/discoveryworld.png",
        "players": ["https://joel.embedtv.live/discoveryworld"],
        "direct_m3u8": None,
    },
    {
        "id": "foodnetwork",
        "name": "Food Network",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/foodnetwork.png",
        "players": ["https://joel.embedtv.live/foodnetwork"],
        "direct_m3u8": None,
    },
    {
        "id": "hgtv",
        "name": "HGTV",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/hgtv.png",
        "players": ["https://joel.embedtv.live/hgtv"],
        "direct_m3u8": None,
    },
    {
        "id": "history",
        "name": "History",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/history.png",
        "players": ["https://joel.embedtv.live/history"],
        "direct_m3u8": None,
    },
    {
        "id": "history2",
        "name": "History 2",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/history2.png",
        "players": ["https://joel.embedtv.live/history2"],
        "direct_m3u8": None,
    },
    {
        "id": "lifetime",
        "name": "Lifetime",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/lifetime.png",
        "players": ["https://joel.embedtv.live/lifetime"],
        "direct_m3u8": None,
    },
    {
        "id": "mtv",
        "name": "MTV",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/mtv.png",
        "players": ["https://joel.embedtv.live/mtv"],
        "direct_m3u8": None,
    },
    {
        "id": "multishow",
        "name": "Multishow",
        "category": "variedades",
        "logo": "https://embedtv.live/assets/images/multishow.png",
        "players": ["https://joel.embedtv.live/multishow"],
        "direct_m3u8": None,
    },
    {
        "id": "masterchef",
        "name": "Masterchef",
        "category": "variedades",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHwO8J5FX3oi_6mn2g4c38ElGF22pIzF6dzA&s",
        "players": [],
        "direct_m3u8": "https://amg00627-banijay-amg00627c9-plex-us-1999.playouts.now.amagi.tv/playlist/amg00627-banijayfast-masterchefbrazil-plexus/playlist.m3u8",
    },
    {
        "id": "tvpaieterno",
        "name": "TV Pai Eterno",
        "category": "variedades",
        "logo": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiQRFQEGyP8x8LglUWRviZrwyVkwZ1dNzeT10ZVp05Hf2-gy_qA7EK9RGqJxHSEIJYmRF-2gHv_EXLrzL2Ne9N9MicLhyphenhyphenogQloQyKdH0bOvapgfVM4F8PqAOdlNo4yPZN2m-QvUB-Z3kUjn3qLnqC6oMmBkpnqLkqZ-brGcIzjrnfFkfOC3SK-1mJg1QGb8/s200/1000094449.png",
        "players": [],
        "direct_m3u8": "https://video09.logicahost.com.br/paieterno/paieterno/playlist.m3u8",
    },
    # ─── NOTÍCIAS ────────────────────────────────────────────────────────────
    {
        "id": "bandnews",
        "name": "BAND NEWS",
        "category": "noticias",
        "logo": "https://embedtv.live/assets/images/bandnews.png",
        "players": ["https://joel.embedtv.live/bandnews"],
        "direct_m3u8": None,
    },
    {
        "id": "cnnbrasil",
        "name": "CNN BRASIL",
        "category": "noticias",
        "logo": "https://embedtv.live/assets/images/cnnbrasil.png",
        "players": ["https://joel.embedtv.live/cnnbrasil"],
        "direct_m3u8": None,
    },
    {
        "id": "globonews",
        "name": "GLOBO NEWS",
        "category": "noticias",
        "logo": "https://embedtv.live/assets/images/globonews.png",
        "players": ["https://joel.embedtv.live/globonews"],
        "direct_m3u8": None,
    },
    {
        "id": "recordnews",
        "name": "RECORD NEWS",
        "category": "noticias",
        "logo": "https://embedtv.live/assets/images/recordnews.png",
        "players": [],
        "direct_m3u8": "https://5cf4a2c2512a2.streamlock.net/8016/8016/playlist.m3u8",
    },
    # ─── INFANTIL ────────────────────────────────────────────────────────────
    {
        "id": "cartoonito",
        "name": "Cartoonito",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/cartoonito.png",
        "players": ["https://joel.embedtv.live/cartoonito"],
        "direct_m3u8": None,
    },
    {
        "id": "cartoonnetwork",
        "name": "Cartoon Network",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/cartoonnetwork.png",
        "players": ["https://joel.embedtv.live/cartoonnetwork"],
        "direct_m3u8": None,
    },
    {
        "id": "discoverykids",
        "name": "Discovery Kids",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/discoverykids.png",
        "players": ["https://joel.embedtv.live/discoverykids"],
        "direct_m3u8": None,
    },
    {
        "id": "gloobinho",
        "name": "Gloobinho",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/gloobinho.png",
        "players": ["https://joel.embedtv.live/gloobinho"],
        "direct_m3u8": None,
    },
    {
        "id": "nickelodeon",
        "name": "Nickelodeon",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/nickelodeon.png",
        "players": ["https://joel.embedtv.live/nickelodeon"],
        "direct_m3u8": None,
    },
    {
        "id": "nickjr",
        "name": "Nick Jr.",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/nickjr.png",
        "players": ["https://joel.embedtv.live/nickjr"],
        "direct_m3u8": None,
    },
    {
        "id": "tooncast",
        "name": "Tooncast",
        "category": "infantil",
        "logo": "https://embedtv.live/assets/images/tooncast.png",
        "players": ["https://joel.embedtv.live/tooncast"],
        "direct_m3u8": None,
    },
    {
        "id": "24h_chaves",
        "name": "24H Chaves",
        "category": "infantil",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3nPr8kkxtzpE7n8tkicqP-ypv37UScmGOfg&s",
        "players": ["https://joel.embedtv.live/24h_chaves"],
        "direct_m3u8": None,
    },
    {
        "id": "24h_dragonball",
        "name": "24H Dragon Ball Z",
        "category": "infantil",
        "logo": "https://m.media-amazon.com/images/S/pv-target-images/6ca7b0149de0cb60400258b879fbbce487d9e399aa4f085b6cb5b8a87c6b2012._SX1080_FMjpg_.jpg",
        "players": ["https://joel.embedtv.live/24h_dragonball"],
        "direct_m3u8": None,
    },
    {
        "id": "24h_naruto",
        "name": "24H Naruto Clássico",
        "category": "infantil",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGx-DdQyfQ_GCURr8cTXo9KS0TV0pyr3wX6A&s",
        "players": ["https://joel.embedtv.live/24h_naruto"],
        "direct_m3u8": None,
    },
    {
        "id": "24h_simpsons",
        "name": "24H Os Simpsons",
        "category": "infantil",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIBByVCiD7yp6GoZuP1gCBzIE3uJajRuVVWA&s",
        "players": ["https://joel.embedtv.live/24h_simpsons"],
        "direct_m3u8": None,
    },
    {
        "id": "24h_odeiachris",
        "name": "24H Todo Mundo Odeia o Cris",
        "category": "infantil",
        "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3FBooVnNu94mJq4wXsASFUBDjd63z90r9Ng&s",
        "players": ["https://joel.embedtv.live/24h_odeiachris"],
        "direct_m3u8": None,
    },
]

# Build a lookup dict for fast access
CHANNELS_BY_ID = {ch["id"]: ch for ch in CHANNELS}
